apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qiot-device-sample
spec:
  commonName: mydeviceid.qiot-project.github.io
  dnsNames:
    - mydeviceid.qiot-project.github.io
  secretName: qiot-device-sample-cert
  issuerRef:
    name: vault-issuer