---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: cert-manager-io/sign/qiot-project-github-io
    server: https://vault.svc.cluster.local:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJVVQzdVVveGlDREV3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRZeE1qTTNNekk0TnpBZQpGdzB5TVRBeU1ETXhOekk0TURaYUZ3MHlNekEwTURReE56STRNRGRhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTJNVEl6TnpNeU9EY3dnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3pueVN6K0wycCs0WC83ZG84Znd5aGMwMTBRSjFaSmNKMAp2QUc0d0pmdW9FeDZ5V09LaTZBTWVaczZlZGFzcmFjaXViVmF0ZU5vNjFvY0h1RTVodzFHZndLbVJaVFNabHVtCllFbXRpZDhZOVJCNnZvU0wxbHhscldSenZuSitURTU5OXZCV1M1amZqTmdISkZuNHM4ZlV6NERDQ0FSODdGcjEKeTdjNHVUQXJ0NzhKbWs2bFdvU211VzlCbUVqYlVHQkJ6L3I2QlV4L1RMMUoxYU1tKzdrWGJBQlp4cjdkb2w3NwpBMmxLTFVLcVJta2ovbUY2VWppUVlNRm9Qdk92eitkdHFuUHNXRUFlOE1UUGZzRW1hRzU1enR1blArMDRiVlpWCjdib01xaG11QnlNb0xhOHZLM01zTU1BRjJqZFhiRzI3UmdGT3dJRXUvcmRMNDlFVE1DQkhBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNJUEQyOQpEWVVBKyt1NkorRjY0RFkvVUlIdHBEQWZCZ05WSFNNRUdEQVdnQlNJUEQyOURZVUErK3U2SitGNjREWS9VSUh0CnBEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSU0w1Zkd6M0QvMk5YdGY3NHJ2c3ZCa1hFMXY5NENnRVowaDEKWG10ZWQ1MzNUWmpnc2JpMjMrdE9Xdll2N0dBanRUUzRrZitYSUV3NHJEY2ROTnlENGhJdUdHSHEvMmNTTEpOKwpwSHdkMW00NDZzRVRQTnRTYmRVd2gvaXlrTXc5d3hYRXN5M05vRTRCQ3poYTZWNzBPK1ZaamZBOGNPOWJOQkFQCjZUanBpMFQzdTNkTVpWaVBGWWZrZ09iaGtJb2RoalUxbG5VVHFUYnNISS9LK3lxVFhqVnVIS3dHY1U4Zy9EYlYKSFptNFpLUnBoUjBJM3kvZ1RYN0tTTVVRSlY2L3ByMUczWHVPbms4QTBJRnI0QjdtRnZicTBaM2Jjd3Y0MUJuWApPSXJzb0pqYTJ3VjlZdEpuRzlsN29mNDBQaVNzTCt0OEdqY29GZzBsVGpNUHArUng2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: cert-manager-token-26mgk
          key: token
