{{- $sa := (lookup "v1" "ServiceAccount" "manufacturing-dev" "default" ) -}}
{{- $bundle := (lookup "v1" "ConfigMap" "manufacturing-dev"  "openshift-service-ca.crt" ) -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "issuer.fullname" . }}-vault
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
spec:
  vault:
    path: {{ .Release.Namespace }}-pki/sign/{{ .Values.baseDomain }} 
    server: {{ .Values.issuer.vault.server }}
    caBundle: {{ get $bundle "service-ca.crt" | b64enc }}
    auth:
      kubernetes:
        role: {{ .Release.Namespace }}-{{ .Values.baseDomain }}
        mountPath: /v1/auth/kubernetes
        secretRef:
          key: token
          {{- range $sa.secrets }}
          {{- if contains  "token" .name }}
          name: {{ .name }}
          {{- end -}}
          {{- end }}
