apiVersion: v1
data:
  application.properties: |-
    quarkus.kubernetes-client.namespace={{ .Release.Namespace }}
    qiot.cert-manager.issuer=ocp-install-issuer-vault
kind: ConfigMap
metadata:
  name: registration-service
