apiVersion: v1
kind: Service
metadata:
  name: plant-manager-service
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-internal
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tcp-external
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: plant-manager-service
    deploymentconfig: plant-manager-service
  sessionAffinity: None
  type: ClusterIP