name: manufacturing-datacenter-install

# Cert Manager Operator OLM
certmanager:
  version: cert-manager.v1.6.0

########## mongo ##########
mongo:
  path: "/var/hpvolumes/mongodb"
  storageCapacity: 5Gi
  MONGODB_ADMIN_PASSWORD: qiotmanufacturingmongoadminpass
  MONGODB_DATABASE: qiotmongo
  MONGODB_PASSWORD: mongopass
  MONGODB_USER: mongouser
  
########## postgresql ##########
postgresql:
  path: "/var/hpvolumes/postgresql"
  storageCapacity: 5Gi
  POSTGRESQL_DATABASE: qiot_manufacturing
  POSTGRESQL_PASSWORD: qiotmanufacturingpassword
  POSTGRESQL_USER: qiotmanufacturing