name: manufacturing-datacenter-install

# Cert Manager Operator OLM
certmanager:
  version: cert-manager.v1.6.0
  
# Influxdb2
influxdb2:
  enabled: True
  adminUser:
    create: true
    organization: "qiot"
    bucket: "manufacturing"
    user: "qiotmanufacturing"
    retention_policy: "0s"
    password: "qiotmanufacturingpassword"
    token: "qiotmanufacturinginfluxdbtoken"
  pdb:
    create: False
