name: manufacturing-datacenter-install

########## mongo ##########
mongo:
  path: "/var/hpvolumes/mongodb"
  storageCapacity: 5Gi
  MONGODB_ADMIN_PASSWORD: qiotmanufacturingmongoadminpass
  MONGODB_DATABASE: qiotmongo
  MONGODB_PASSWORD: mongopass
  MONGODB_USER: mongouser
  
########## Influxdb2 ##########
influxdb2:
  enabled: True
  adminUser:
    create: true
    organization: "qiot"
    bucket: "manufacturing"
    user: "qiotmanufacturing"
    retention_policy: "0s"
    password: "qiotmanufacturingpassword"
    token: "qiotmanufacturinginfluxdbtoken"
  pdb:
    create: False

########## postgresql ##########
postgresql:
  path: "/var/hpvolumes/postgresql"
  storageCapacity: 5Gi
  POSTGRESQL_DATABASE: qiot_manufacturing
  POSTGRESQL_PASSWORD: qiotmanufacturingpassword
  POSTGRESQL_USER: qiotmanufacturing
